# Generated by Django 4.2.1 on 2023-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotool', '0002_keywords_suggestion_delete_googlesearchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords_suggestion',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
