# Generated by Django 4.2.1 on 2023-11-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seotool', '0013_keywords_suggestion_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords_suggestion',
            name='author',
        ),
    ]
