# Generated by Django 4.2.1 on 2023-11-09 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=250)),
                ('time_consumption', models.IntegerField()),
                ('cuisine', models.CharField(choices=[('Polish', '🇵🇱'), ('German', '🇩🇪'), ('Italian', '🇮🇹'), ('French', '🇫🇷'), ('American', '🇺🇸'), ('Spanish', '🇪🇸'), ('Japanese', '🇯🇵'), ('Indian', '🇮🇳'), ('Other', '')], max_length=25)),
                ('recipe_image', models.ImageField(upload_to='uploads/recipes')),
                ('guidelines', models.CharField(max_length=5000)),
                ('recipe_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
