# Generated by Django 4.2.1 on 2023-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('Polish', 'Polish'), ('German', 'German'), ('Italian', 'Italian'), ('French', 'French'), ('American', 'American'), ('Spanish', 'Spanish'), ('Japanese', 'Japan'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=50),
        ),
    ]
