# Generated by Django 4.2.1 on 2023-11-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_consumption',
            new_name='time',
        ),
    ]
