# Generated by Django 4.2.1 on 2023-11-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_time_consumption_recipe_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='step_number',
            new_name='step',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('Breafkfest', 'Breakfast'), ('Brunch', 'Brunch'), ('Dinner', 'Dinner'), ('Supper', 'Supper')], max_length=50),
        ),
    ]
