# Generated by Django 4.2.1 on 2023-11-12 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_favorite_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite_recipe',
            unique_together={('user', 'recipe')},
        ),
    ]
