# Generated by Django 4.2.1 on 2023-11-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_average_rating_recipe_total_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Dinner', 'Dinner'), ('Supper', 'Supper')], max_length=50),
        ),
    ]
