# Generated by Django 4.2.1 on 2023-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_favourite_quote_user_alter_favourite_quote_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_quote',
            name='author',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
