# Generated by Django 4.2.1 on 2023-11-05 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0004_remove_favourite_quote_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite_quote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favourite_quote',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='favourite_quote',
            name='quote',
            field=models.CharField(max_length=2500),
        ),
    ]
